name: CI Transfermarkt

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      - 'main'
      - 'feature/*'
    paths:
      - '**'
      - '.github/workflows/ci.yml'

  # Allow manually trigger
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python "3.10"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Install Dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.create true
          poetry config virtualenvs.path .venv
          poetry install --no-interaction --no-root

      - name: Analyze Syntax
        run: |
          source .venv/bin/activate
          invoke lint

      - name: Run Tests
        run: |
          source .venv/bin/activate
          invoke ucover

      - name: Report Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
